name: skype_clone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  permission_handler: ^5.0.1+1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  shimmer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
